language: ruby
env:
  global:
  - NAME="Nobody Nobody But You, Oh.."
  - EMAIL="jcouyang@thoughtworks.com"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_5c6b0be318f3_key -iv $encrypted_5c6b0be318f3_iv
  -in deploy.enc -out deploy -d
- eval $(ssh-agent)
- chmod 600 deploy
- ssh-add deploy
install:
- sudo add-apt-repository -y ppa:cassou/emacs
- sudo apt-get -qq update
- sudo apt-get -qq -f install
- sudo apt-get -qq install emacs24 emacs24-el
- wget https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-1-amd64.deb
- sudo dpkg -i pandoc-1.13.2-1-amd64.deb
- curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
- export PATH="/home/travis/.cask/bin:$PATH"
script:
- cask install
- "./ci/preserve_timestamp.sh"
- "./ci/import.sh"
- "./ci/ci-publish.sh"
after_success:
- "./ci/ci-push.sh"
